// まだ ConfigEffect（CE）のテストが無い設定キーと、書く予定のチケット（PLAN §6.2・CR-14。T-09）。
// テストを書いたチケットは、自分の PR でここから自分のキーを消す。

/// まだ ConfigEffect のテストが無いキー → 書く予定のチケット。空になったら網羅完了（T-43 の受け入れ条件）。
enum ConfigEffectPending {
    static let owners: [String: String] = [
        "timeZone": "T-22",
        "session.blockGapSeconds": "T-22",
        "session.idleCloseSeconds": "T-22",
        "session.allowReopen": "T-22",
        "session.maxParts": "T-22",
        "session.maxDurationSeconds": "T-22",
        "llm.modelID": "T-22",
        "vault.path": "T-28",
        "vault.marker": "T-28",
        "device.includeVolumes": "T-13",
        "device.excludeVolumes": "T-13",
        "device.maxScanDepth": "T-14",
        "device.stabilityFastPathSeconds": "T-14",
        "device.stabilityIntervalSeconds": "T-14",
        "device.stabilityChecks": "T-14",
        "audio.hashChunkBytes": "T-14",
        "device.mountMode": "T-15",
        "device.scanIntervalSeconds": "T-15",
        "device.snapshotMaxAgeSeconds": "T-38",
        "cleanup.deleteSourceAudio": "T-38",
        "cleanup.deleteEvaluationBackoffSeconds": "T-38",
        "cleanup.deleteResultTimeoutSeconds": "T-38",
        "audio.timeoutFactor": "T-16",
        "audio.minTimeoutSeconds": "T-16",
        "audio.durationToleranceSeconds": "T-16",
        "audio.freeSpaceMultiplier": "T-16",
        "audio.freeSpaceMarginBytes": "T-16",
        "audio.stagingMaxBytes": "T-16",
        "audio.inboxRetain": "T-18",
        "cleanup.deleteNormalizedAfterTranscribe": "T-18",
        "retry.maxAttempts": "T-18",
        "retry.backoffSeconds": "T-18",
        "transcription.whisperModelID": "T-17",
        "transcription.language": "T-17",
        "transcription.threads": "T-17",
        "transcription.timeoutFactor": "T-17",
        "transcription.minTimeoutSeconds": "T-17",
        "transcription.maxTimeoutSeconds": "T-17",
        "transcription.minChars": "T-17",
        "transcription.vad.enabled": "T-17",
        "transcription.vad.modelID": "T-17",
        "transcription.vad.threshold": "T-17",
        "transcription.vad.minSpeechDurationMs": "T-17",
        "transcription.vad.minSilenceDurationMs": "T-17",
        "transcription.vad.speechPadMs": "T-17",
        "llm.contextSize": "T-21",
        "llm.temperature": "T-21",
        "llm.topP": "T-21",
        "llm.maxOutputTokens": "T-21",
        "llm.requestTimeoutSeconds": "T-21",
        "llm.maxCharsPerRequest": "T-20",
        "llm.maxSecondsPerRequest": "T-20",
        "llm.chunkOverlapChars": "T-20",
        "llm.analysis.sections.summary.heading": "T-27",
        "llm.analysis.sections.timeline.heading": "T-27",
        "llm.analysis.sections.key_points.heading": "T-27",
        "llm.analysis.sections.tasks.heading": "T-27",
        "llm.analysis.sections.decisions.heading": "T-27",
        "llm.analysis.sections.ideas.heading": "T-27",
        "llm.analysis.sections.tags.heading": "T-27",
        "llm.analysis.sections.timeline.enabled": "T-27",
        "llm.analysis.order": "T-27",
        "obsidian.defaultTags": "T-27",
        "obsidian.wiki.folderTemplate": "T-27",
        "obsidian.wiki.filenameTemplate": "T-27",
        "obsidian.wiki.linkDailyNote": "T-27",
        "obsidian.wiki.linkAdjacentDays": "T-27",
        "obsidian.wiki.linkTags": "T-27",
        "obsidian.wiki.linkOnlyExisting": "T-27",
        "obsidian.wiki.maxLinks": "T-27",
        "obsidian.wiki.vaultIndexCacheSeconds": "T-29",
        "obsidian.maxTitleBytes": "T-26",
        "obsidian.raw.filenameTemplate": "T-26",
        "obsidian.raw.timestampIntervalSeconds": "T-26",
        "obsidian.raw.partBoundaryHeading": "T-26",
        "obsidian.raw.folderTemplate": "T-33",
        "cleanup.deleteSkippedSource": "T-39",
    ]
}
